### ISSUE TITLE
Crash while pregening with chunky

### ISSUE THREAD

**Issue by iiiodel** [mactso/HarderSpawners#10]
Hello. Sorry for oppening a closed issue again. In the modpack I'm currently using, I'm getting a crash caused by the HarderSpawners mod while pregenning the world with chunky. I also have modernfix mod. There are other people who are getting the same error I'm getting while pregenning. There is even a person who encountered this problem while playing normally and crashed the game. But I cannot verify this issue because I have not encountered it myself. I am ready to provide the necessary logs and data. If you want, I can also share the modpack I use and the discord server of that pack. Is it possible to find a solution to this issue? I think you will encounter the same problem when you make a dedicated server with the same mod pack and pregen it.

**Comment by Micaxs** [comment]
```[18:43:08] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: null
        Index: 34
        Listeners:
                0: HIGH
                1: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                2: NORMAL
                3: ASM: net.thirdlife.iterrpg.IterRpgMod@7a3069fe tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                4: ASM: net.mcreator.unusualend.UnusualendMod@6f52f6c6 tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                5: ASM: net.mcreator.clutteredmod.LuphieclutteredmodMod@5fa32e5d tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                6: ASM: class com.dynamic_view.event.EventHandler onDedicatedServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                7: ASM: class mods.thecomputerizer.musictriggers.server.ServerEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                8: ASM: net.mcreator.corundumguardian.CorundumguardianMod@100f61bc tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                9: net.minecraftforge.eventbus.EventBus$$Lambda$1529/0x00007f12dc6d6e40@2b5a2e1
                10: ASM: net.minecraftforge.common.ForgeInternalHandler@3ef10f54 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                11: ASM: class com.mlib.contexts.OnSpawned onServerTickEnd(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                12: ASM: class com.mlib.contexts.OnServerTick onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                13: ASM: class com.connectivity.event.EventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                14: net.minecraftforge.eventbus.EventBus$$Lambda$1529/0x00007f12dc6d6e40@1be640ac
                15: ASM: class shadows.placebo.util.PlaceboTaskQueue tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                16: net.minecraftforge.eventbus.EventBus$$Lambda$1529/0x00007f12dc6d6e40@72e7fa53
                17: ASM: class noobanidus.mods.lootr.entity.EntityTicker onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                18: net.minecraftforge.eventbus.EventBus$$Lambda$1529/0x00007f12dc6d6e40@55582ce0
                19: ASM: class noobanidus.mods.lootr.block.entities.TileTicker serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                20: ASM: net.mcreator.borninchaosv.BornInChaosV1Mod@69957336 tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                21: ASM: class insane96mcp.insanelib.util.scheduled.ScheduledTasks onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                22: ASM: net.mcreator.predators.PredatorsMod@7f813ce4 tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                23: ASM: class tschipp.carryon.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                24: ASM: class com.cupboard.event.EventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                25: ASM: net.mcreator.nourishednether.NourishedNetherMod@22b5091c tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                26: ASM: net.mcreator.enlightened_end.EnlightenedEndMod@40a0b61f tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                27: ASM: net.mcreator.createconfectionery.CreateConfectioneryMod@a0e1e86 tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                28: ASM: net.mcreator.weaverscosmetics.WeaversCosmeticsMod@2ad58b11 tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                29: ASM: class se.mickelus.tetra.ServerScheduler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                30: net.minecraftforge.eventbus.EventBus$$Lambda$1529/0x00007f12dc6d6e40@7ad53e00
                31: ASM: class vazkii.quark.base.handler.RecipeCrawlHandler onTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                32: ASM: class com.blamejared.crafttweaker.impl.event.CTCommonEventHandler serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                33: ASM: class com.simibubi.create.foundation.events.CommonEvents onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                34: ASM: com.mactso.harderspawners.events.ServerTickHandler@322c9a9f onServerTickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                35: ASM: journeymap.common.events.forge.ForgeServerEvents@3bdc3c77 onServerTickEvent(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                36: ASM: me.hypherionmc.simplerpc.SimpleRPCForge@311807fc serverTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                37: ASM: com.natamus.collective.forge.events.RegisterCollectiveEvents@18b0b43a onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
                38: ASM: me.lucko.spark.forge.ForgeTickHook@1809bc68 onTick(Lnet/minecraftforge/event/TickEvent;)V
                39: ASM: me.lucko.spark.forge.ForgeTickReporter@47bfabab onTick(Lnet/minecraftforge/event/TickEvent;)V
                40: LOWEST
                41: ASM: com.github.alexthe666.citadel.ServerProxy@a238b3c onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.remove(ArrayList.java:981)
        at TRANSFORMER/harderspawners@1.19.1-43.2.24.0/com.mactso.harderspawners.events.ServerTickHandler.onServerTickEvent(ServerTickHandler.java:42)
        at TRANSFORMER/harderspawners@1.19.1-43.2.24.0/com.mactso.harderspawners.events.__ServerTickHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
        at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
        at TRANSFORMER/forge@43.3.7/net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:849)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:843)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
        at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
        at java.base/java.lang.Thread.run(Thread.java:840)
[18:43:08] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?] {}
        at java.util.ArrayList$Itr.remove(ArrayList.java:981) ~[?:?] {}
        at com.mactso.harderspawners.events.ServerTickHandler.onServerTickEvent(ServerTickHandler.java:42) ~[HarderSpawners-1.19.1-43.2.24.0.jar%23538!/:1.19.1-43.2.24.0] {re:classloading}
        at com.mactso.harderspawners.events.__ServerTickHandler_onServerTickEvent_ServerTickEvent.invoke(.dynamic) ~[HarderSpawners-1.19.1-43.2.24.0.jar%23538!/:1.19.1-43.2.24.0] {re:classloading,pl:eventbus:B}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2351!/:?] {}
        at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:849) ~[forge-1.19.2-43.3.7-universal.jar%23694!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:843) ~[server-1.19.2-20220805.130853-srg.jar%23689!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23689!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23689!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:infernal-expansion.mixins.json:common.MixinMinecraftServer,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:mobifier.mixins.json:MixinMinecraftServer,pl:mixin:APP:neruina.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:blockswap.mixins.json:MixinMinecraftServer,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin}
[18:43:08] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID b82e7e27-ae36-4b50-97ec-244bb956967a```

Similar issue, world pregen with chunky causes this specific crash.

**Comment by mactso** [comment]
Hi sorry for the late response.  I was sick back then.   I see this is 1.19.1 .  I'm working on Harder Spawners now and I'll try to review that issue.  Also, I'm much better with bugs reported in Discord.
